### ISSUE TITLE
Allow spellchecker for latex (.tex) files

### ISSUE THREAD

**Issue by jfrob27** [jupyterlab-contrib/spellchecker#102]
Hi, I use jupyter lab for coding and writing latex documents. It would be wonderful if we could activate spellchecker in .tex files opened in jupyter lab.

**Comment by krassowski** [comment]
You can already do that. Just go to Settings (/Advanced Settings Editor) -> Spellchecker and change `mimeTypes` to include latex. I tested that the following works for `.tex` files in JupyterLab 3.2:

```json
{
    "mimeTypes": [
        "text/plain",
        "text/x-ipythongfm",
        "text/x-latex"
    ],
}
```

Ideally we would provide a list of mime types in to choose from. This would be a nice enhancment.

**Comment by jfrob27** [comment]
Great! I was suspecting a trick like this, but I did not know how to do it.
Many thanks!
