### ISSUE TITLE
Support for spelling suggestions in the text editor, and support more common formats by default.

### ISSUE THREAD

**Issue by fperez** [jupyterlab-contrib/spellchecker#125]
At least with JupyterLab 3.6.1 (I didn't test before), the misspelling highlight works in the text editor, but the context menu of the text editor does not show alternate spelling suggestions.

Also, it would be great to activate it by default for `.tex` files and `.rst`, two common formats in our community.

Here is what I'm getting with v 0.7.2 on JLab 3.6.1:

![image](https://user-images.githubusercontent.com/57394/223935273-e13087b8-ed3c-48f4-a397-474082ce3a92.png)

BTW - huge thanks for this great extension! I just [added it to our campus hub](https://github.com/berkeley-dsep-infra/datahub/pull/4344) and will provide further feedback, as students and instructors use it more.

**Comment by fperez** [comment]
cc @facusapienza21 so we track improvements on this front for our stat 159 students.

**Comment by fperez** [comment]
MMh, btw - this may be a firefox-specific issue! I happened to open the same setup from Chrome, and spell checking suggestions work fine in Chrome.

Feel free to close if it's a false alarm, but I'll leave it here for now in case it is something that is coming from the extension and can be fixed, instead of a pure ffox problem (I have no clue).

**Comment by krassowski** [comment]
@fperez please upgrade to [version 0.7.3](https://github.com/jupyterlab-contrib/spellchecker/tree/v0.7.3) which was released last month and has spellchecker enabled by default in RST and LaTeX :)

If you want to enable it manually in the older version, your settings should include: `text/x-rst` and `text/x-latex` rather than `text/rst` and `text/latex` as on the screenshot.

I will close this one as completed but please reopen if the problem persists in newer version and after correcting the MIME types in settings.

**Comment by krassowski** [comment]
> note that in this case, I got the latex one [from the JupyterLab docs](https://jupyterlab.readthedocs.io/en/2.2.x/user/file_formats.html#latex) so that should be fixed, I guess? (and would be good to list the correct mimetypes for other common files as understood by jupyterlab, so people can get the right answer for this one :)

Good point. Some background: the mime-type is used to discover language using CodeMirror5 machinery which is different from our JupyterLab machinery hence the difference. There will be probably be changes to this with CodeMirror6.

> Also - is there a reason why it can't be configured by file extension and has to be done by mimetype? For most users that would be a bit easier, I think...

It could be both I think. Or we could have a nice list of accepted mimetypes built-in the settings (this one gets tricky when extensions add support for novel languages/document types but could be handled too).

**Comment by krassowski** [comment]
> Our hubs default to pulling from conda-forge, and that still has 0.7.2 as of today, which tripped me up.

Whoops, I forgot there is no auto-merge bot on this one. https://github.com/conda-forge/jupyterlab-spellchecker-feedstock/pull/5 is in, 0.7.3 should be up in a few hours.

**Comment by fperez** [comment]
Awesome, thx! I'll update our hub image tomorrow then, it's very straightforward.  Delighted to have this on our systems :)
