### ISSUE TITLE
Spellcheck runs in code cells but not markdown cells

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab-contrib/spellchecker#143]
In JupyterLab 4.1.8, the spellchecker is (correctly) highlighting spelling errors in code cells, but not identifying any spelling errors in markdown cells.

<img width="373" alt="image" src="https://github.com/jupyterlab-contrib/spellchecker/assets/82988/34151906-f821-4c2a-a8b2-b9bb9b4f2b5b">

In the devtools console, I see the following warnings as I type, though it's not clear to me what might be raising them or whether that issue relates to the spellchecker's incorrect behaviour?

```text
highlights.ts:343 Could not get highlights: TypeError: Cannot read properties of undefined (reading 'isReady')
    at Qt.requestHighlights (highlights.ts:217:20)
    at a.factory [as _factory] (jlab_core.b91074b1e57242ddcd31.js?v=b91074b1e57242ddcd31:1:1758915)
    at a._execute (jlab_core.b91074b1e57242ddcd31.js?v=b91074b1e57242ddcd31:1:1757383)
    at o (jlab_core.b91074b1e57242ddcd31.js?v=b91074b1e57242ddcd31:1:1756803)

```

**Comment by krassowski** [comment]
For me spellchecking in markdown works great. This error you show comes from `jupyterlab-lsp`, not from spellchecker; it is possible that that error could be breaking the editor logic and thus the spellchecker.

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/b159ae2736b26463d8cc8f0ef78f4b2ce9913370/packages/jupyterlab-lsp/src/features/highlights.ts#L208

Can you open an issue on https://github.com/jupyter-lsp/jupyterlab-lsp showing how to reproduce this error (and listing versions of  the extension, and language servers installed).

**Comment by psychemedia** [comment]
@krassowski ok, thanks (though I would expect it to be more likley that any `jupyterlab-lsp` error would cause issues with code cells rather than markdown cells?)

**Comment by krassowski** [comment]
In Lab 4 LSP is also supported in Markdown cells.

**Comment by psychemedia** [comment]
It seems there's a conflict with [`jupysql-plugin`](https://github.com/ploomber/jupysql-plugin) that breaks the spell checker in markdown cells ([issue](https://github.com/ploomber/jupysql-plugin/issues/113))
