### ISSUE TITLE
How can I add a portuguese dictionary?

### ISSUE THREAD

**Issue by chicolucio** [jupyterlab-contrib/spellchecker#31]
Hi. I'm from Brazil and I'd like to use a portuguese (pt_BR) dictionary. How can I install and activate a new dictionary?

**Comment by krassowski** [comment]
The Portuguese dictionary is already available in the recent versions (but for now it is pt_PT, not pt_BR). We are working on better multi-lingual support (which requires re-working how dictionaries are fetched as if we keep adding new languages with the old mechanism it will become a significant memory burden for JupyterLab).

**Comment by krassowski** [comment]
This is now possible with the new 0.6.0 version, please see the instructions in the readme and the example [here](https://github.com/jupyterlab-contrib/spellchecker#adding-dictionaries---example).

**Comment by chicolucio** [comment]
Thanks!
