### ISSUE TITLE
Rename to spellchecker?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/spellchecker#47]
What do you think about renaming the extension to spellchecker (dropping the jupyterlab_ prefix) since it already is in organization that has jupyterlab in name? The PyPI package would still be called jupyterlab-spellchecker, but the npm one would become just `@jupyterlab-contrib/spellchecker` rather than `@jupyterlab-contrib/jupyterlab_spellchecker`.

**Comment by ocordes** [comment]
Sounds good, in german we say "Doppeltgemoppelt" which means the you have a double redundancy in the word! Frédéric mentioned that at the moment the extension is reachable with the same name as before @ijmbarr/jupyterlab_spellchecker . I'm not sure how to deal with that. I mean at least the old package should indicate that there is a new package or include a dependency if this is possible to guarantee a smooth transition.

**Comment by krassowski** [comment]
@fcollonval what do you think? If you are for, could you please rename to repo? My logic is that if this change should proceed than it is better to do it now to avoid transitioning twice.

> at the moment the extension is reachable with the same name as before @ijmbarr/jupyterlab_spellchecker

good point. I think that we can make one release that updates the repository links, but keeps the @ijmbarr namespace and then change the namespace (and potentially the name) in the next release. Does it sound ok?

**Comment by ocordes** [comment]
As far as I understood, with jupyterlab > 3 the extension should be installed via pip or conda not with jupyter labextension ? How long do we need to support the jupyterlab 2.x or can we freeze the old @ijmbarr/jupyterlab_spellchecker for version 2.x and jupyter-contrib/spellchecker for version 3.x ?

**Comment by krassowski** [comment]
Yes, I prepared the package for the pip-installable "federated extension" in #48. It is named jupyterlab-spellchecker, but not published yet. I agree that we probably should keep installation instructions like: "for JupyterLab 2.x install @ijmbarr/jupyterlab_spellchecker" (which is what I did in #48).

**Comment by fcollonval** [comment]
Yeah, first of I want to point out that when transferring a project the original owner may choose if the name should be kept or changed. In this case good new ijmbarr says he does not care (https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/6) 😃 

Reading this discussion, I like the conclusion - aka pointing out that for JupyterLab 2 the install should keep the _old_ name. But for JupyterLab 3, I'm ok to create a new npm package named **@jupyterlab-contrib/spellchecker**.

**Comment by fcollonval** [comment]
> If you are for, could you please rename to repo?

Done

**Comment by fcollonval** [comment]
I let this open as it will require some links update.
