### ISSUE TITLE
Allow to use online dictionaries

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/spellchecker#76]
> But how can we implement a language description which is able to load files directly from the network? With lang.json this is easy, okay, one can argue "download everything you need" is sufficient ;-)

I have mixed feelings here. I did think about making another setting for "online dictionaries" so that one would go to the advanced settings and add something like:

```json
{
    "ignore": ["JupyterLab", "Notebook", "Notatnik"],
    "language": "pl_PL-online",
    "onlineDictionaries": [
        {
            "id": "pl_PL-online",
            "aff": "http://some-url/pl_PL.aff",
            "dic": "http://some-url/pl_PL.dic",
            "name": "polski (Polska)"
        }
    ]
}
```

I'm not convinced that this is necessary now, given that the dictionaries loaded locally from the disk are more reliable, but I see that for some very specific use cases this might be useful. I will open a new issue to track this one.

_Originally posted by @krassowski in https://github.com/jupyterlab-contrib/spellchecker/issues/74#issuecomment-852084074_

**Comment by ocordes** [comment]
This is an excellent idea! My motivation was to have something in the server installation which I can prepare for many users. User settings are good for individual configurations, but this should be sufficient. You're right local dictionaries are more reliable.
